{
  "build": {
    "builder": "railway/php:8.3",
    "extensions": [
      "gd",
      "pdo_mysql",
      "pdo",
      "mbstring",
      "openssl",
      "curl",
      "xml",
      "fileinfo",
      "json",
      "tokenizer",
      "session"
    ]
  }
}
